const EventsArray = [
  {
    id: 1,
    title: "CAPA Airline Leader Summit – Americas 2019",
    description:
      "The CAPA Airline Leader Summit – Americas 2025, held April ...",
    year: "2019",
    month: "April",
    country: "Italy",
    location: "Da Nang, Vietnam",
    image: "/Images/CAPAAirline.png",
    link: "#",
    continent: "Africa",
    catagory: "Air show",
    Days: "3 Days Left",
  },
  {
    id: 2,
    title: "Passenger Terminal Expo 2020",
    description:
      "The world’s leading international airport conference and exhibition, and host ...",
    year: "2020",
    month: "April",
    country: "Africa",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/april2.png",
    link: "#",
    catagory: "Award",
    Days: "8 Days Left",
  },
  {
    id: 3,
    title: "Philippine Airport Modernization and Expansion Summit 2020",
    description:
      "Over the next four years, the Philippine government, under the ...",
    year: "2020",
    month: "April",
    country: "Japan",
    continent: "Europe",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/april3.png",
    link: "#",
    catagory: "Award",
    Days: "23 Days Left",
  },
  {
    id: 4,
    title: "ACI EUROPE Regional Airports Conference and Exhibition 2021",
    description:
      "The ACI EUROPE Regional Airports Conference and Exhibition is the ...",
    year: "2021",
    month: "April",
    country: "France",
    continent: "North America",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/april4.png",
    link: "#",
    catagory: "Award",
    Days: "28 Days Left",
  },
  {
    id: 5,
    title: "Airport Show 2021",
    description:
      "The Airport Show will bring together leading airport suppliers, service ...",
    year: "2021",
    month: "May",
    country: "Dubai",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/Airport-Show.png",
    link: "#",
    catagory: "Award",
    Days: "36 Days Left",
  },
  {
    id: 6,
    title: "CAPA Airline Leader Summit – Airlines in Transition 2021",
    description:
      "The Airline Leader Summit - Airlines in Transition is CAPA’s ...",
    year: "2021",
    month: "May",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/CAPAAirline.png",
    link: "#",
    catagory: "Award",
    Days: "38 Days Left",
  },
  {
    id: 7,
    title: "Aviation Festival Americas 2022",
    description:
      "Business models. Technology. Sustainability. For the Americas aviation industry. Now in its ...",
    year: "2022",
    month: "May",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/may1.png",
    link: "#",
    catagory: "Award",
    Days: "40 Days Left",
  },
  {
    id: 8,
    title: "Airports Canada Conference 2022",
    description:
      "Airports play a critical role in the interconnected economy, acting ...",
    year: "2022",
    month: "May",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/may2.png",
    link: "#",
    catagory: "Award",
    Days: "52 Days Left",
  },
  {
    id: 9,
    title: "Transport Logistic 2022",
    description:
      "Transport Logistic 2025 offers unparalleled insights, groundbreaking innovations, and transformative ...",
    year: "2022",
    month: "June",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/june1.png",
    link: "#",
    catagory: "Award",
    Days: "59 Days Left",
  },
  {
    id: 10,
    title: "Americas GHI Conference 2022",
    description:
      "GATEWAY TO AMERICAS Discover new business opportunities in the world’s fastest-growing ...",
    year: "2022",
    month: "June",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/june2.png",
    link: "#",
    catagory: "Award",
    Days: "60 Days Left",
  },
  {
    id: 11,
    title: "EAA AirVenture 2022",
    year: "2022",
    month: "July",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/july1.jpg",
    link: "#",
    catagory: "Award",
    Days: "108 Days Left",
  },
  {
    id: 12,
    title: "Airport Experience Summit 2023",
    description:
      "The ACI World's Airport Experience Summit is the leading global ...",
    year: "2023",
    month: "September",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/sep1.jpeg",
    link: "#",
    catagory: "Award",
    Days: "157 Days Left",
  },
  {
    id: 13,
    title: "Future Travel Experience Global 2023",
    description:
      "The definitive event for innovators, technologists, designers, collaborators, and gamechangers FTE ...",
    year: "2023",
    month: "September",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/sep2.jpeg",
    link: "#",
    catagory: "Award",
    Days: "158 Days Left",
  },
  {
    id: 14,
    title: "Aviation Forum 2023",
    year: "2023",
    month: "September",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/sep3.jpeg",
    link: "#",
    catagory: "Award",
    Days: "108 Days Left",
  },
  {
    id: 15,
    title: "International GSE Expo 2023",
    description:
      "The Premier Event Dedicated to the Advancement of the Ground ...",
    year: "2023",
    month: "September",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/sep4.jpeg",
    link: "#",
    catagory: "Award",
    Days: "165 Days Left",
  },
  {
    id: 16,
    title: "African GHI Stakeholders’ Conference 2023",
    description:
      "Championing African Aviation Growth GHI’s 8th African Stakeholders’ Conference will bring ...",
    year: "2023",
    month: "September",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/sep5.jpeg",
    link: "#",
    catagory: "Award",
    Days: "172 Days Left",
  },
  {
    id: 17,
    title: "World Aviation Festival 2024",
    description:
      "Business models. Technology. Sustainability. Innovation. For the global aviation industry The World ...",
    year: "2024",
    month: "Octobar",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/oct.jpeg",
    link: "#",
    catagory: "Award",
    Days: "186 Days Left",
  },
  {
    id: 18,
    title: "Inter Airport Europe 2024",
    description: "Inter Airport Europe is a leading event for the global ...",
    year: "2024",
    month: "Octobar",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/oct2.jpeg",
    link: "#",
    catagory: "Award",
    Days: "186 Days Left",
  },
  {
    id: 19,
    title: "ACI-NA Annual Conference and Exhibition 2024",
    description:
      "ACI-NA is excited to bring the airport industry together again ...",
    year: "2024",
    month: "Octobar",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/oct3.jpeg",
    link: "#",
    catagory: "Award",
    Days: "204 Days Left",
  },
  {
    id: 20,
    title: "Annual GHI Conference 2024",
    description:
      "Connect the industry that connects the world   The GHI Annual, the ...",
    year: "2024",
    month: "November",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/nov.jpeg",
    link: "#",
    catagory: "Award",
    Days: "220 Days Left",
  },
  {
    id: 21,
    title: "International Aviation Issues Seminar 2025",
    description:
      "Discover the latest developments in international air travel and trade ...",
    year: "2025",
    month: "December",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/dec.png",
    link: "#",
    catagory: "Award",
    Days: "251 Days Left",
  },
  {
    id: 22,
    title: "Annual GHI Conference 2025",
    description:
      "Connect the industry that connects the world. The GHI Annual, the ...",
    year: "2025",
    month: "December",
    country: "Athens",
    continent: "Asia",
    location: "Marina Bay Sands, Singapore",
    image: "/Images/dec1.jpeg",
    link: "#",
    catagory: "Award",
    Days: "256 Days Left",
  },
];
export default EventsArray;
