const GateArray = [
  {
    id: 1,
    name: "BGR135",
    Images: "/Images/Access.png",
    image: "/Images/g1.png",
    company: "Custom4U",
    country: "USA",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "Barcode reader",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 2,
    name: "BGR700",
    Images: "/Images/Access.png",
    image: "/Images/g2.png",
    company: "Custom4U",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MRZ",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
  {
    id: 3,
    name: "Access is LSR 120",
    Images: "/Images/Access.png",
    image: "/Images/g3.png",
    company: "Custom4U",
    country: "China",
    features: "Rugged design",
    power: "AC",
    scanningmethod: "OCR",
    readingmethod: "Full-page",
    imageCapure: "Visible",
  },
  {
    id: 4,
    name: "Ticket Monster",
    Images: "/Images/alfi.png",
    image: "/Images/g4.png",
    company: "Custom4U",
    country: "Japan",
    features: "Audio indicator",
    power: "Battery",
    scanningmethod: "NFC/RFID",
    readingmethod: "Swip",
    imageCapure: "IR",
  },
  {
    id: 5,
    name: "BGR 504 pro",
    Images: "/Images/DESKO.png",
    image: "/Images/g5.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "AC",
    scanningmethod: "Contact smart card",
    readingmethod: "Full-page",
    imageCapure: "UV",
  },
  {
    id: 6,
    name: "PENTA Scanner BGR",
    Images: "/Images/DESKO.png",
    image: "/Images/g6.png",
    company: "Epson",
    country: "Germany",
    features: "Rugged design",
    power: "Battery",
    scanningmethod: "Passport, ID, VISA scanning",
    readingmethod: "Swip",
    imageCapure: "Visible",
  },
  {
    id: 7,
    name: "IER 602",
    Images: "/Images/IER.png",
    image: "/Images/g7.png",
    company: "Epson",
    country: "Germany",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "ePassport/RFID option",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 8,
    name: "iBGR / 200",
    Images: "/Images/KCT.png",
    image: "/Images/g8.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MSR",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
];

export default GateArray;
