const HandheldArray = [
  {
    id: 1,
    name: "SG20B",
    Images: "/Images/Access.png",
    image: "/Images/Hand1.png",
    company: "Custom4U",
    country: "USA",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "Barcode reader",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 2,
    name: "RF Reader",
    Images: "/Images/Access.png",
    image: "/Images/Hand2.png",
    company: "Custom4U",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MRZ",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
  {
    id: 3,
    name: "Access is LSR 120",
    Images: "/Images/Access.png",
    image: "/Images/Hand3.png",
    company: "Custom4U",
    country: "China",
    features: "Rugged design",
    power: "AC",
    scanningmethod: "OCR",
    readingmethod: "Full-page",
    imageCapure: "Visible",
  },
  {
    id: 4,
    name: "Xenon XP 1950h",
    Images: "/Images/alfi.png",
    image: "/Images/Hand4.png",
    company: "Custom4U",
    country: "Japan",
    features: "Audio indicator",
    power: "Battery",
    scanningmethod: "NFC/RFID",
    readingmethod: "Swip",
    imageCapure: "IR",
  },
  {
    id: 5,
    name: "1980i",
    Images: "/Images/DESKO.png",
    image: "/Images/Hand5.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "AC",
    scanningmethod: "Contact smart card",
    readingmethod: "Full-page",
    imageCapure: "UV",
  },
  {
    id: 6,
    name: "1920i",
    Images: "/Images/DESKO.png",
    image: "/Images/Hand6.png",
    company: "Epson",
    country: "Germany",
    features: "Rugged design",
    power: "Battery",
    scanningmethod: "Passport, ID, VISA scanning",
    readingmethod: "Swip",
    imageCapure: "Visible",
  },
  {
    id: 7,
    name: "1911i",
    Images: "/Images/IER.png",
    image: "/Images/Hand7.png",
    company: "Epson",
    country: "Germany",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "ePassport/RFID option",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 8,
    name: "1910i",
    Images: "/Images/KCT.png",
    image: "/Images/Hand8.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MSR",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
];

export default HandheldArray;
