export const OCRArray = [
  {
    id: 1,
    name: "PENTA Scanner 4X",
    Images: "/Images/Access.png",
    image: "/Images/OCR1.png",
    company: "Custom4U",
    country: "USA",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "Barcode reader",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 2,
    name: "70X9",
    Images: "/Images/Access.png",
    image: "/Images/OCR2.png",
    company: "Custom4U",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MRZ",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
  {
    id: 3,
    name: "ID-1 GO",
    Images: "/Images/Access.png",
    image: "/Images/OCR3.png",
    company: "Custom4U",
    country: "China",
    features: "Rugged design",
    power: "AC",
    scanningmethod: "OCR",
    readingmethod: "Full-page",
    imageCapure: "Visible",
  },
  {
    id: 4,
    name: "Combo Scan ID & Passport Scanner",
    Images: "/Images/Access.png",
    image: "/Images/OCR4.png",
    company: "Custom4U",
    country: "Japan",
    features: "Audio indicator",
    power: "Battery",
    scanningmethod: "NFC/RFID",
    readingmethod: "Swip",
    imageCapure: "IR",
  },
  {
    id: 5,
    name: "Mobile Workstation 83X3M",
    Images: "/Images/DESKO.png",
    image: "/Images/OCR5.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "AC",
    scanningmethod: "Contact smart card",
    readingmethod: "Full-page",
    imageCapure: "UV",
  },
  {
    id: 6,
    name: "Gemalto Intelligent OEM",
    Images: "/Images/DESKO.png",
    image: "/Images/OCR6.png",
    company: "Epson",
    country: "Germany",
    features: "Rugged design",
    power: "Battery",
    scanningmethod: "Passport, ID, VISA scanning",
    readingmethod: "Swip",
    imageCapure: "Visible",
  },
  {
    id: 7,
    name: "Gemalto OEM Document Reader AT10K",
    Images: "/Images/IER.png",
    image: "/Images/OCR7.png",
    company: "Epson",
    country: "Germany",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "ePassport/RFID option",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 8,
    name: "Gemalto Intelligent Document",
    Images: "/Images/KCT.png",
    image: "/Images/OCR8.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MSR",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
];
