const PrintersArray = [
  {
    id: 1,
    name: "TK180",
    image: "/Images/Printer1.png",
    company: "Custom4U",
    country: "USA",
    type: "Thermal",
  },
  {
    id: 2,
    name: "TK180 METAL",
    image: "/Images/printer2.png",
    company: "Custom4U",
    country: "Germany",
    type: "Metal",
  },
  {
    id: 3,
    name: "TK202",
    image: "/Images/printer3.png",
    company: "Custom4U",
    country: "China",
    type: "Inkjet",
  },
  {
    id: 4,
    name: "TK202III METAL",
    image: "/Images/printer4.png",
    company: "Custom4U",
    country: "Japan",
    type: "Laser",
  },
  {
    id: 5,
    name: "TK302III",
    image: "/Images/printer5.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 6,
    name: "TK302III METAL",
    image: "/Images/printer6.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 7,
    name: "TK862",
    image: "/Images/printer7.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 8,
    name: "TM-L500A",
    image: "/Images/printer8.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 9,
    name: "F9860",
    image: "/Images/printer9.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 10,
    name: "9870",
    image: "/Images/printer10.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 11,
    name: "i420",
    image: "/Images/printer11.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 12,
    name: "400",
    image: "/Images/printer12.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 13,
    name: "560",
    image: "/Images/printer13.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 14,
    name: "BP 70",
    image: "/Images/printer14.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 15,
    name: "ET 7000",
    image: "/Images/printer15.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 16,
    name: "ATP3",
    image: "/Images/printer16.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 17,
    name: "MAP",
    image: "/Images/printer17.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 18,
    name: "ATP6",
    image: "/Images/printer18.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 19,
    name: "KPM180H",
    image: "/Images/printer19.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 20,
    name: "KPM180H-LL",
    image: "/Images/printer20.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 21,
    name: "KPM862",
    image: "/Images/printer21.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 22,
    name: "9890S",
    image: "/Images/printer22.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 23,
    name: "BT 700",
    image: "/Images/printer23.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
];

export default PrintersArray;
