const SelfbagArray = [
  {
    id: 1,
    name: "Self Baggage-Drop",
    Images: "/Images/Access.png",
    image: "/Images/self1.png",
    company: "Custom4U",
    country: "USA",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "Barcode reader",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 2,
    name: "R-Type",
    Images: "/Images/Access.png",
    image: "/Images/self2.png",
    company: "Custom4U",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MRZ",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
  {
    id: 3,
    name: "Fast Bag",
    Images: "/Images/Access.png",
    image: "/Images/self3.png",
    company: "Custom4U",
    country: "China",
    features: "Rugged design",
    power: "AC",
    scanningmethod: "OCR",
    readingmethod: "Full-page",
    imageCapure: "Visible",
  },
  {
    id: 4,
    name: "AIR.GO ON",
    Images: "/Images/alfi.png",
    image: "/Images/self4.png",
    company: "Custom4U",
    country: "Japan",
    features: "Audio indicator",
    power: "Battery",
    scanningmethod: "NFC/RFID",
    readingmethod: "Swip",
    imageCapure: "IR",
  },
  {
    id: 5,
    name: "AIR.GO 1.0",
    Images: "/Images/DESKO.png",
    image: "/Images/self5.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "AC",
    scanningmethod: "Contact smart card",
    readingmethod: "Full-page",
    imageCapure: "UV",
  },
  {
    id: 6,
    name: "AIR.GO 2.0",
    Images: "/Images/DESKO.png",
    image: "/Images/self6.png",
    company: "Epson",
    country: "Germany",
    features: "Rugged design",
    power: "Battery",
    scanningmethod: "Passport, ID, VISA scanning",
    readingmethod: "Swip",
    imageCapure: "Visible",
  },
  {
    id: 7,
    name: "BagDrop",
    Images: "/Images/IER.png",
    image: "/Images/self7.png",
    company: "Epson",
    country: "Germany",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "ePassport/RFID option",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 8,
    name: "Seamless Bagdrop",
    Images: "/Images/KCT.png",
    image: "/Images/self8.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MSR",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
];

export default SelfbagArray;
