const WearableArray = [
  {
    id: 1,
    name: "BGR135",
    Images: "/Images/Access.png",
    image: "/Images/w1.png",
    company: "SelfServ XK7",
    country: "USA",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "Barcode reader",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 2,
    name: "V Tag",
    Images: "/Images/Access.png",
    image: "/Images/w2.png",
    company: "Custom4U",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MRZ",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
  {
    id: 3,
    name: "Self Check-in Kiosh",
    Images: "/Images/Access.png",
    image: "/Images/w3.png",
    company: "Custom4U",
    country: "China",
    features: "Rugged design",
    power: "AC",
    scanningmethod: "OCR",
    readingmethod: "Full-page",
    imageCapure: "Visible",
  },
  {
    id: 4,
    name: "SCK-2.3",
    Images: "/Images/alfi.png",
    image: "/Images/w4.png",
    company: "Custom4U",
    country: "Japan",
    features: "Audio indicator",
    power: "Battery",
    scanningmethod: "NFC/RFID",
    readingmethod: "Swip",
    imageCapure: "IR",
  },
  {
    id: 5,
    name: "IS-SelfCheckin C3",
    Images: "/Images/DESKO.png",
    image: "/Images/w5.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "AC",
    scanningmethod: "Contact smart card",
    readingmethod: "Full-page",
    imageCapure: "UV",
  },
  {
    id: 6,
    name: "Self Check-in Kiosk",
    Images: "/Images/DESKO.png",
    image: "/Images/w6.png",
    company: "Epson",
    country: "Germany",
    features: "Rugged design",
    power: "Battery",
    scanningmethod: "Passport, ID, VISA scanning",
    readingmethod: "Swip",
    imageCapure: "Visible",
  },
  {
    id: 7,
    name: "919",
    Images: "/Images/IER.png",
    image: "/Images/w7.png",
    company: "Epson",
    country: "Germany",
    features: "Audio indicator",
    power: "AC",
    scanningmethod: "ePassport/RFID option",
    readingmethod: "Full-page",
    imageCapure: "IR",
  },
  {
    id: 8,
    name: "V1 Biometric",
    Images: "/Images/KCT.png",
    image: "/Images/w8.png",
    company: "Epson",
    country: "Germany",
    features: "LED Indicator",
    power: "Battery",
    scanningmethod: "MSR",
    readingmethod: "Swip",
    imageCapure: "UV",
  },
];

export default WearableArray;
