const vendorsData = [
  {
    id: 1,
    image: "/Images/pak.png",
    name: "Pakistan",
    continent: "Asia",
    country: "🇵🇰",
    videoTutorials: 7,
    documents: 0,
    freeTrial: true,
    clc: true,
    mobileApp: true,
    dcs: true,
    iataPartner: false,
    Details: "➡️",
  },
  {
    id: 2,
    Details: "➡️",
    image: "/Images/engs.png",
    name: "England",
    continent: "Europe",
    country: "🇮🇹",
    videoTutorials: 0,
    documents: 0,
    freeTrial: false,
    clc: true,
    mobileApp: false,
    dcs: true,
    iataPartner: true,
  },
  {
    id: 3,
    Details: "➡️",
    image: "/Images/france.jpeg",
    name: "France",
    continent: "Europe",
    country: "🇨🇳",
    videoTutorials: 3,
    documents: 2,
    freeTrial: true,
    clc: false,
    mobileApp: false,
    dcs: true,
    iataPartner: false,
  },
  {
    id: 4,
    Details: "➡️",
    image: "/Images/america.jpeg",
    name: "America",
    continent: "North America",
    country: "🇺🇸",
    videoTutorials: 5,
    documents: 1,
    freeTrial: false,
    clc: true,
    mobileApp: true,
    dcs: false,
    iataPartner: true,
  },
  {
    id: 5,
    Details: "➡️",
    image: "/Images/germany.png",
    name: "Germany",
    continent: "Europe",
    country: "🇨🇿",
    videoTutorials: 2,
    documents: 0,
    freeTrial: true,
    clc: false,
    mobileApp: false,
    dcs: true,
    iataPartner: true,
  },
  {
    id: 6,
    Details: "➡️",
    image: "/Images/canada.jpeg",

    name: "Canada",
    continent: "North America",
    country: "🇲🇽",
    videoTutorials: 1,
    documents: 3,
    freeTrial: false,
    clc: true,
    mobileApp: false,
    dcs: false,
    iataPartner: false,
  },
  {
    id: 7,
    Details: "➡️",
    image: "/Images/Italy.png",
    name: "Italy",
    continent: "Europe",
    country: "🇪🇸",
    videoTutorials: 4,
    documents: 2,
    freeTrial: true,
    clc: true,
    mobileApp: false,
    dcs: true,
    iataPartner: true,
  },
  {
    id: 8,
    Details: "➡️",
    image: "/Images/Max.png",

    name: "Maxico",
    continent: "North America",
    country: "🇬🇧",
    videoTutorials: 6,
    documents: 1,
    freeTrial: false,
    clc: false,
    mobileApp: true,
    dcs: true,
    iataPartner: false,
  },
  {
    id: 9,
    image: "/Images/india.png",
    Details: "➡️",
    name: "India",
    continent: "Asia",
    country: "🇫🇷",
    videoTutorials: 3,
    documents: 0,
    freeTrial: true,
    clc: true,
    mobileApp: false,
    dcs: false,
    iataPartner: true,
  },
  {
    id: 10,
    Details: "➡️",
    image: "/Images/b.jpeg",

    name: "Barazil",
    continent: "South Amercia",
    country: "🇦🇺",
    videoTutorials: 2,
    documents: 1,
    freeTrial: false,
    clc: false,
    mobileApp: true,
    dcs: true,
    iataPartner: false,
  },
];
export default vendorsData;
