const vendorsData = [
  {
    id: 1,
    image: "/Images/logo1.png",
    name: "Pakistan",
    continent: "Karachi",
    country: "🇵🇰",
    videoTutorials: 7,
    documents: 0,
    freeTrial: true,
    clc: true,
    mobileApp: true,
    dcs: true,
    iataPartner: false,
    Details: "➡️",
  },
  {
    id: 2,
    Details: "➡️",
    image: "/Images/logo2.png",
    name: "A-ICE",
    continent: "Europe",
    country: "🇮🇹",
    videoTutorials: 0,
    documents: 0,
    freeTrial: false,
    clc: true,
    mobileApp: false,
    dcs: true,
    iataPartner: true,
  },
  {
    id: 3,
    Details: "➡️",
    image: "/Images/logo3.png",
    name: "Accelero",
    continent: "Asia",
    country: "🇨🇳",
    videoTutorials: 3,
    documents: 2,
    freeTrial: true,
    clc: false,
    mobileApp: false,
    dcs: true,
    iataPartner: false,
  },
  {
    id: 4,
    Details: "➡️",
    image: "/Images/logo4.png",
    name: "AFM Solutions",
    continent: "North America",
    country: "🇺🇸",
    videoTutorials: 5,
    documents: 1,
    freeTrial: false,
    clc: true,
    mobileApp: true,
    dcs: false,
    iataPartner: true,
  },
  {
    id: 5,
    Details: "➡️",
    image: "/Images/logo5.png",

    name: "Air Dispatch",
    continent: "Europe",
    country: "🇨🇿",
    videoTutorials: 2,
    documents: 0,
    freeTrial: true,
    clc: false,
    mobileApp: false,
    dcs: true,
    iataPartner: true,
  },
  {
    id: 6,
    Details: "➡️",
    image: "/Images/logo6.png",

    name: "Altair",
    continent: "North America",
    country: "🇲🇽",
    videoTutorials: 1,
    documents: 3,
    freeTrial: false,
    clc: true,
    mobileApp: false,
    dcs: false,
    iataPartner: false,
  },
  {
    id: 7,
    Details: "➡️",
    image: "/Images/logo7.png",
    name: "Amadeus",
    continent: "Europe",
    country: "🇪🇸",
    videoTutorials: 4,
    documents: 2,
    freeTrial: true,
    clc: true,
    mobileApp: false,
    dcs: true,
    iataPartner: true,
  },
  {
    id: 8,
    Details: "➡️",
    image: "/Images/logo8.png",

    name: "APG",
    continent: "North America",
    country: "🇬🇧",
    videoTutorials: 6,
    documents: 1,
    freeTrial: false,
    clc: false,
    mobileApp: true,
    dcs: true,
    iataPartner: false,
  },
  {
    id: 9,
    image: "/Images/logo9.png",
    Details: "➡️",
    name: "Aviation Safety Management Systems",
    continent: "North America",
    country: "🇫🇷",
    videoTutorials: 3,
    documents: 0,
    freeTrial: true,
    clc: true,
    mobileApp: false,
    dcs: false,
    iataPartner: true,
  },
  {
    id: 10,
    Details: "➡️",
    image: "/Images/logo10.png",

    name: "Avinet",
    continent: "Australia",
    country: "🇦🇺",
    videoTutorials: 2,
    documents: 1,
    freeTrial: false,
    clc: false,
    mobileApp: true,
    dcs: true,
    iataPartner: false,
  },
];
export default vendorsData;
