export const Mobilearray = [
  {
    id: 1,
    name: "TK180",
    image: "/Images/m1.png",
    company: "Custom4U",
    country: "USA",
    type: "Thermal",
  },
  {
    id: 2,
    name: "TK180 METAL",
    image: "/Images/m2.png",
    company: "Custom4U",
    country: "Germany",
    type: "Metal",
  },
  {
    id: 3,
    name: "TK202",
    image: "/Images/m3.png",
    company: "Custom4U",
    country: "China",
    type: "Inkjet",
  },
  {
    id: 4,
    name: "TK202III METAL",
    image: "/Images/m4.png",
    company: "Custom4U",
    country: "Japan",
    type: "Laser",
  },
  {
    id: 5,
    name: "TK302III",
    image: "/Images/m24.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 6,
    name: "TK302III METAL",
    image: "/Images/m6.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 7,
    name: "TK862",
    image: "/Images/m7.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 8,
    name: "TM-L500A",
    image: "/Images/m8.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 9,
    name: "F9860",
    image: "/Images/m9.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 10,
    name: "9870",
    image: "/Images/m10.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 11,
    name: "i420",
    image: "/Images/m11.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 12,
    name: "400",
    image: "/Images/m12.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 13,
    name: "560",
    image: "/Images/m13.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 14,
    name: "BP 70",
    image: "/Images/m14.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 15,
    name: "ET 7000",
    image: "/Images/m15.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 16,
    name: "ATP3",
    image: "/Images/m16.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 17,
    name: "MAP",
    image: "/Images/m17.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 18,
    name: "ATP6",
    image: "/Images/m18.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 19,
    name: "KPM180H",
    image: "/Images/m19.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 20,
    name: "KPM180H-LL",
    image: "/Images/m20.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 21,
    name: "KPM862",
    image: "/Images/m21.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 22,
    name: "9890S",
    image: "/Images/m22.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
  {
    id: 23,
    name: "BT 700",
    image: "/Images/m23.png",
    company: "Epson",
    country: "Germany",
    type: "Thermal",
  },
];
